baseurl = "https://fumagalli-mf.vision/"
theme = "../.."
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Matteo Fumagalli"
title = "Matteo Fumagalli"
#disqusshortname = ""
pluralizelisttitles = false
disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
blog = "blog/:slug/"

[params]
dateform = " 2 Jan 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Personal blog"
copyright = "Copyright © {year} - Matteo Fumagalli"
# copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/logo.jpg"
faviconfile = "img/logo.jpg"
highlightjs = true
progressively = true
share = false
# Share to googleplus, twitter, fb, linkedin by default
# disable by setting share_on_<social network> = false
# example: share_on_googleplus = false
latestpostcount = 5
github = "Matt-Mf"
#email = ""
#linkedin = "john-example-aa80ue8è"
#twitter = "example"
#facebook = "facebook_id"
#instagram = "instagram_id"
#itch_io = "itch_io_id"
#social_banner = "img/banner.png"
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
githubRepo = "Privacy Policy"
small_banner_logo = false

[params.colors]
identifier = "#a45a04bf"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"
